### ISSUE TITLE
AutoSKLearn or top-k-count bug

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-dynamic-neural-architecture#77]
AutoSKLearn should get a perfect score in top-k-count for training data. It is not. Either AutoSKLearn is wrong or the metric is.

**Comment by orionw** [comment]
Notes: we discussed that due to how Autosklearn works by taking the best pipeline from the closest dataset, moving to the next closest dataset and choosing the best pipeline there, etc, it should be returning at least the top 1 every time.  Thus, all regret scores should be 0 and top-k count should be at least 1/k
